### ISSUE TITLE
Message click event object

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#10]
It would be useful to get the index of the message clicked and the type (send/recieve) in the message click event object.

**Comment by pec1985** [comment]
I can include this as a feature request but just to let you know, there is no way right now to remove a message from the screen

**Comment by sindresorhus** [comment]
That's not a problem. My usecase is that I have an array that contains all the send/recieve messages with additional metadata. When I click a message I need to use that metadata, but I have no idea what index the message is.
