### ISSUE TITLE
Option to show Copy menu when message clicked

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#11]
Can we have an option to show the [copy menu tooltip](http://developer.apple.com/library/IOS/#documentation/iPhone/Reference/UIMenuController_Class/UIMenuController.html) when a message is clicked?

**Comment by pec1985** [comment]
I wonder if this could be done in JS with the Ti.UI.Clipboard API, I will check

**Comment by sindresorhus** [comment]
Titanium currently has no support for UIMenuController. Ti.UI.Clipboard API is currently only usable to set and the clipboard, not showing the copy/paste tooltip. There is a [feature request on JIRA](http://jira.appcelerator.org/browse/TIMOB-2832) on it.
