### ISSUE TITLE
backgroundColor default

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#15]
The `backgroundColor` property of the `textArea` should default to the color of the built-in SMS app: [`#dae1eb`](https://skitch.com/sindresorhus/f3sr2/finder)

**Comment by pec1985** [comment]
Do you think we should default that? I'll do that and hopefully no one will complain. Thanks for your input.

**Comment by sindresorhus** [comment]
Yes, since you're going for a replica of the built-in SMS app look, in my opinion it should have that color as default.
