### ISSUE TITLE
saveMessages()

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#19]
There is a method to load an array of messages. Could we also have a method that does the opposite?

To make the conversation persistent it would be useful if it was also possible to save the conversation to an array in the format it uses to load an array.

**Comment by pec1985** [comment]
I just created an array to store the indexes, working on that other issue, so at the same time I could take advantage of that array to do what you are asking for. In any event, this can be done in JS very easily. 

Let me see what I can do.

**Comment by sindresorhus** [comment]
I'm already doing it in javascript. But instead of having a separate array that I need to keep in sync with the conversation, it would be cleaner if there was a method to save the conversation to an array. In my opinion this would make the module even easier to use, since almost everyone would want to save the conversation for persistence between sessions.
