### ISSUE TITLE
Bug report kami

### ISSUE THREAD

**Issue by kamikze** [pec1985/TiSMSView#2]
Old:

reference:
http://developer.appcelerator.com/question/124922/textfield-with-keyboard-like-smswhats-app#answer-217736

Could you help me with this?

**Comment by pec1985** [comment]
Yeah, I saw the Q&A. I will look into it today. Also, try switching to the other branch in the repository

Pedro

**Comment by kamikze** [comment]
the 1.9 version wasnt recognized, just tried that one. The example runs fine now =)

ill try to implement it into my app next, now it just gives a square input field and no send button, only the text is show.

**Comment by pec1985** [comment]
I'll push version 2 today, I also need to clean up the sample app.js and update the docs.

PS: make sure the smsview.bundle is the Resources

**Comment by pec1985** [comment]
Responded to the Q&A.

Let me know how it goes.

**Comment by kamikze** [comment]
ah thnx pedro, adding the smsview.bundle to the resources fixed the layout ;)

didnt really read i needed to add the smsview.bundle to the resources, maby you could add that one to in the 1,2,3 steps to install your module.

ill be finishing my messaging system today with your module. And really your module is so nice tnx alot!

**Comment by pec1985** [comment]
In glad you found it useful. I will add that to the steps of installing the module.

Also, very important to use version 2.0, unless you wish to see random app crashes, hehe. V2.0 has some major memory fixes, compared to earliest versions, and a couple of new features, like an "empty()" function and click events on the messages themselves.

Anyway, thanks again for the input and I'm looking forward to seen the app in the AppStore, let me know.

Pedro

**Comment by kamikze** [comment]
I am using 2.0 now, the loadMessages() function is quite usefull. Havent had a crash yet, so far so good =)

On the loadMessages, when i add alot of messages, it does not scroll to the bottom. But when you press the textfield and the keyboard comes up, it does scroll to the bottom.
Perhaps a function that scrolls to the bottom, or add this to the loadMessages().

Maby for a future update the clouds could have a dateTime property ( string preffered ), where you can add a date from which the message was send. Would be usefull for a user to see that.

Hope this is userfull to you, i'll be looking forwards for future updates on this module =)

~Kami

**Comment by kamikze** [comment]
Ah sorry, just tested on a real iPhone and it does scroll to the bottom, for some reason it wont do that in the simulator. 

But i did found a bug, my app supports portrait and landscape in the entire app. When i switch to landscape, the texfield and button are invisible and cutting the clouds from where it should be.

Should be nice if landscape works ;)

**Comment by pec1985** [comment]
I just updated the documentation about the smsview.bundle

(Edited documentation/smsview.md)

About the scrolling on a bunch of messages, I still need to tweak it a bit, but it should run fine in the device, like you said.

Closing issue for now.
