### ISSUE TITLE
Label between messages

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#20]
To make it even more like the built-in SMS app. You should add support for adding labels into the conversation. In the same style as the screenshot. There's a lot of use cases for this; like to separate conversation, add some additonal info, ...

Example:

``` javascript
addLabel('19. july 2011');
sendMessage('Lorem ipsum');
```

![SMS app](https://img.skitch.com/20110917-d7k4c5ws711h9b4irg5m3bfsuj.png)

**Comment by pec1985** [comment]
Although this is an inevitable feature, I will put this in standby for now I will work on it next weekend, as it requires a lot of work.

**Comment by bentindall** [comment]
Hi there, is there any update on this feature? It would be very useful. I can provide assistance if you'd like help with it.

**Comment by pec1985** [comment]
No update yet, too busy with other things.... if you want to provide assistance in anyway, shape, or form, please do so. I want to get this done by the end of next week.

;)
