### ISSUE TITLE
UI bug toolbar

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#23]
There is an UI bug with the toolbar when running the example app on a physical iPhone. This doesn't happen in the simulator.

This happens when the textArea is focused:

![ui bug](https://img.skitch.com/20110918-xjyhj3eyjn588sb547usicj4t3.png)

_Tested with commit 78eb297f0181c4f212d788e2f70b40657e8c8cdb_

**Comment by pec1985** [comment]
Cannot reproduce, tested the sample app plus a real app I have made.

**Comment by pec1985** [comment]
Fixed in commit 3facd5def6
