### ISSUE TITLE
maxLines overflow

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#26]
If I specify `maxLines: 5` or higher in the textArea it will expand beyond it's view when in landscape orientation on iPhone.
Make sure min-maxLines never go higher than the navBar.

![overflow example](https://img.skitch.com/20110924-r941eejgpfw1his519tu96pnr8.png)

**Comment by pec1985** [comment]
The programmer should be smart enough to set the max-lines to a reasonable number. Play with the max-lines number and set one that you're happy with, otherwise this feature should be removed.

Close.
