### ISSUE TITLE
background on sendButton is hidden

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#28]
The background of the sendButton is hidden if the SMS view is created with the `sendButtonDisabled` is set to `true`.

``` javascript
var textArea = Ti.SMSView.createView({
    sendButtonDisabled: true
});
```

![button disabled bug](https://img.skitch.com/20110924-cfsww63hecp9u4np7fwpryb32a.png)

**Comment by pec1985** [comment]
I will have to look into it, for now just disable it after the creation of it.
