### ISSUE TITLE
buttonTitle attribute not working

### ISSUE THREAD

**Issue by jamesdevries** [pec1985/TiSMSView#3]
I am using the following:

var textArea = Ti.Pedro.createSMSView({
    backgroundColor: '#b7d4fa',
    assets:'assets',
    buttonTitle: 'Post',
    autocorrect: true,
});

and the screen does not show the control at all.

**Comment by pec1985** [comment]
Good to know, I'll take a look at it ASAP  .

**Comment by pec1985** [comment]
Fixed

**Comment by pec1985** [comment]
Please download version 2.2 - which contains this fix
