### ISSUE TITLE
label should not be clickable

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#34]
If I have the textArea focused and try to hit the view background to blur it and accidentally hit a label, nothing happens, since the label absorbs the click event. This should not happen.

**Comment by pec1985** [comment]
why should it not be clickable? What if I want to be able to copy the text of the label?

**Comment by sindresorhus** [comment]
Because it's a label, what kind of actions do you need on a label? Except copy of course, which is a `hold` event, not `tap` (click).

**Comment by pec1985** [comment]
Fixed
