### ISSUE TITLE
buttonTitle not working

### ISSUE THREAD

**Issue by VinzGhyz** [pec1985/TiSMSView#37]
Hello,

Thanks really much for your awesome module !

It works great but everytime I try to modify the button title my app simply crashes. Maybe it is due to the fact that i'm running iOS 5.

If you could help me out on this one, maybe it's all my fault

Bye!

**Comment by pec1985** [comment]
Thanks for the heads up, I am running iOS 5 and not seeing the problem. Can you provide a sample test case? and, do you have a crash log?

FYI: The title must be set when creating the button, and cannot be modified later on, as far as I know.

**Comment by VinzGhyz** [comment]
I'm using the sample app.js provided with the module and have only modified the buttonTitle property on the declaration of the view. Also, I had to modify the win.open() function as it wasn't working with modal set to true.

Every time i get those bugs, the app just closes itself right after the splashscreen and the log appears to be just
[DEBUG] Session started
[DEBUG] Session did end with error (null)

**Comment by pec1985** [comment]
I need to see the crash log, if you can reproduce it, open the "console" application and grab the log from there. I'm not able to reproduce it right here.

**Comment by VinzGhyz** [comment]
Here's a gist of the build.log whether I did it with win set to modal or not. It crashes in the two cases. As soon as I get rid of the buttonTitle : 'Ajouter' line everything works with no problems
https://gist.github.com/1285337

**Comment by pec1985** [comment]
Try to do a clean build. Also, that's the build.log, I need the crash log.

**Comment by pec1985** [comment]
Got it to crash on me as well. It was working in the past, so I'll see what's going on. I'll try to have an update this evening.

**Comment by pec1985** [comment]
There is definitely something broken, I'll fix it as soon as I can
