### ISSUE TITLE
Scroll to bottom after sending a message

### ISSUE THREAD

**Issue by bentindall** [pec1985/TiSMSView#38]
Is there a way to make the list scroll down to the bottom after sending a message? Is this feature already supported?

**Comment by pec1985** [comment]
Isn't it working already?

**Comment by sindresorhus** [comment]
It's working for me.

**Comment by bentindall** [comment]
It works up to a point.. If you send more than a page/page and a half's worth of messages, it doesn't scroll to the bottom anymore. I was also wondering if there could be a "textArea.scrollToBottom()" function, so that you could manually call it, say for example when you opened the window.

**Comment by sindresorhus** [comment]
@bentindall If you send multiple messages in a burst, there is a bug with the animation that prevents it from scrolling to the last item. Disabling animation temporary fixes this.
