### ISSUE TITLE
Please update the Appcelerator Marketplace

### ISSUE THREAD

**Issue by caspahouzer** [pec1985/TiSMSView#39]
In the Appcelerator Marketplace seems to be an old version. There isn't the "addLabel" function within. And I'm poorly not able to get my own compiled version running :-/

**Comment by pec1985** [comment]
Yes, you are correct. I have not update the Markertplace version yet, I'll do it whenever I have a chance.

I'll send you a PM with a working build from this repo.

**Comment by caspahouzer** [comment]
Is the marketplace updated?

**Comment by pec1985** [comment]
Done
