### ISSUE TITLE
Hide the send-area

### ISSUE THREAD

**Issue by caspahouzer** [pec1985/TiSMSView#40]
I have a feature request. In my app, I have a community messaging system. There I have an Incoming and an Outgoing mailbox. In the Outgoing mailbox I only want to show the messages, but not the possibilty to send a new one.

Is that possible to have a function: hideTextArea or something like that?

**Comment by pec1985** [comment]
Whenever I have a chance, I will add a new component that will only show the scroll view with then messages. Will that fit your needs?

Will try to do it within next week.

**Comment by netpro2k** [comment]
It would also be very nice if we could create a expanding textbox independently as well. Would love to use this in my app but already have my own method of displaying messages.

**Comment by pec1985** [comment]
That second request if probably not going to happen any time soon.
