### ISSUE TITLE
Crashing on iOS 5

### ISSUE THREAD

**Issue by euforic** [pec1985/TiSMSView#41]
opens window fine on ios 4.3 but crashes on iOS 5;

**Comment by pec1985** [comment]
it's not crashing in iOS 5 for me. Are you running the version from the marketplace or from the repository? Does the sample app.'s crash? How does your code look like?

**Comment by euforic** [comment]
Sorry for the lack of explanation I know how annoying those tickets are lol.  Here is a gist of my usage https://gist.github.com/1298846  and I have tested the version from the marketplace and git repo

**Comment by euforic** [comment]
I think this may have been an issue with conflicting modal windows. Thanks
