### ISSUE TITLE
Installing on iOS device produces error

### ISSUE THREAD

**Issue by caspahouzer** [pec1985/TiSMSView#44]
In simulator everything looks fine, but installing the app with Ti.SmsView on device, it produces

``` javascript
[ERROR] Error: Traceback (most recent call last):
  File "/Users/sebastian/Library/Application Support/Titanium/mobilesdk/osx/1.7.3/iphone/builder.py", line 1305, in main
    execute_xcode("iphoneos%s" % iphone_version,args,False)
  File "/Users/sebastian/Library/Application Support/Titanium/mobilesdk/osx/1.7.3/iphone/builder.py", line 1066, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Users/sebastian/Library/Application Support/Titanium/mobilesdk/osx/1.7.3/iphone/run.py", line 39, in run
    sys.exit(rc)
SystemExit: 65
```

on build

**Comment by pec1985** [comment]
I need to see your tiapp.xml as well as the javascript line of code where you are including the module. 

When including the module, it has to be all case-sensitive.

```
Ti.SMSView = require('ti.smsview');
```

**Comment by caspahouzer** [comment]
My XML

``` javascript
<modules>
        <module version="1.0">ti.smsview</module>
</modules>
```

and here is my code: http://pastie.org/2766202

**Comment by pec1985** [comment]
Open the project in Xcode (found in build/iphone/) and build it from there. I've been using this module for one opt my apps for over a month now, and not seeing any problems while running it on the device.

**Comment by euforic** [comment]
I am having the same issue. I compiled the module from current git repo. 

Tested on 1.7.5 and 1.8.0v20111104160655

**Comment by pec1985** [comment]
Check at the bottom of this wiki page:
http://wiki.appcelerator.org/display/guides/iOS+Module+Development+Guide

Look for: Compiling modules with Xcode 4.2

This might be the problem you're running into.

**Comment by euforic** [comment]
Yep that fixed it thanks!
