### ISSUE TITLE
scrolling randomly not working

### ISSUE THREAD

**Issue by albert0m** [pec1985/TiSMSView#56]
I don't know what I'm doing wrong, but it seems like that if I click and drag the scrollview, sometimes the scrollview doesn't move. You have to touch it several time and doing different gestures, until it works again.

**Comment by pec1985** [comment]
Do you have anything else in the window? maybe a view on top or something? what section of the scrollview are you touching? I have never seen this, please provide as much info as possible. Also, a small pastie or gist with a sample test case would really help out.

Thanks!

**Comment by albert0m** [comment]
I know, it's kinda hard to describe.
I don't do anything special, it's just inside a container view (so that I can resize it the way I want it), and that's it.
My customer told me that when it happens they fix it draggin it down, and after the scrollview bounces, it works again. ?!?

**Comment by albert0m** [comment]
ok, I looked into it and the problem was that I added it to a view, not a win.. I was suggested to do then in order to make the smsview not fullscreen but of another size. Weird behavior anyways.
