### ISSUE TITLE
how to add a image to the textArea.recieveMessage()

### ISSUE THREAD

**Issue by samueleastdev** [pec1985/TiSMSView#59]
is it possible to add a image to the receive message function?

textArea.recieveMessage("I want to pass a image in here that has been pull from database");

i have been trying the following

```
var image = Ti.UI.createImageView({
image:'http://wwwimages.adobe.com/www.adobe.com/downloadcenter/images/shockwave/shockwave_128.jpg'
});
textArea.recieveMessage(image.toBlob());
```

any suggestions thanks

**Comment by pec1985** [comment]
It should work: https://github.com/pec1985/ExpandableTextArea/blob/master/example/app.js#L94

**Comment by pec1985** [comment]
Closing issue, no response
