### ISSUE TITLE
PSD of assets

### ISSUE THREAD

**Issue by sindresorhus** [pec1985/TiSMSView#7]
If you have the PSD files for the assets. Would you consider releasing them?

Would be nice to be able to modify the assets.

**Comment by pec1985** [comment]
The files in the assets are png files, then have to have those specific names. What do you mean by PSD? (PhotoShop?) how would that be used?

**Comment by sindresorhus** [comment]
Yes, if you have the source files (psd? = photoshop) for creating the png files. So I can for example add more colors, or remove the gloss from the bubble.

**Comment by pec1985** [comment]
No, that's really not going to be possible, at least at this time.

If you look inside the the assets/smsview.bundle (which is a folder) the images have this format:

```
    GreenBalloonLeft.png
```

If you need another color, the image must have that name pattern: Green (capital "G") which is the color and Left (capilat"L") which is the side of the image. You can take any of those images, open them up in an image editor, like PS, and change the color, brightness, etc.

**Comment by sindresorhus** [comment]
Ok, where did you get the images from?

_You should add to the docs that it is possible to add a custom color, and how to do it, like you've described here ;-)_

**Comment by pec1985** [comment]
Good idea, will update the documentation
